Separate language-pack-* installationh on debian (for Raspberry Pi)

diff --git a/install b/install
--- a/install
+++ b/install
@@ -31,12 +31,13 @@ case $uname in
     if [ -f /etc/debian_version ]; then
       sudo apt-get update
       sudo apt-get install aptitude
-      sudo aptitude install language-pack-en language-pack-ja \
+      sudo aptitude install \
         build-essential git zsh curl sudo vim \
         zlib1g-dev libssl-dev libsqlite3-dev sqlite3 libxml2-dev libxslt1-dev \
         libgdbm-dev libbz2-dev libreadline-dev \
         bison libreadline6-dev libyaml-dev libncurses5-dev \
         bvi jq ngrep autossh
+      sudo aptitude install language-pack-en language-pack-ja || echo "not found language packs"
       # TODO: add ripgrep/fd/cheat/wrk/bat when added
     elif [ -f /etc/redhat-release ]; then
       sudo yum update
