Update debian packages and remove linuxbrew

diff --git a/install b/install
--- a/install
+++ b/install
@@ -60,30 +60,14 @@ case $uname in
         zlib1g-dev libssl-dev libsqlite3-dev sqlite3 libxml2-dev libxslt1-dev \
         libgdbm-dev libbz2-dev libreadline-dev \
         bison libreadline6-dev libyaml-dev libncurses5-dev \
-        bvi jq gron ngrep autossh \
-        direnv \
-        imagemagick \
-        ripgrep \
-        rclone \
-        mpv
-      sudo aptitude install language-pack-en language-pack-ja || echo "not found language packs"
-
-      if [ ! -d /home/linuxbrew ]; then
-        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
-        echo 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"' >> $HOME/.zprofile
-        eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
-      fi
-      eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
-      brew update
-      ulimit -n 4096 # ffmpeg installs many packages so we need many file descriptors
-      brew install \
+        poppler-utils \
         ffmpeg \
-        ghq peco \
-        fig \
         jq autossh \
         direnv \
         imagemagick \
-        ripgrep
+        ripgrep \
+        rclone
+      sudo aptitude install language-pack-en language-pack-ja || echo "not found language packs"
     elif [ -f /etc/redhat-release ]; then
       sudo yum update
       sudo yum groupinstall "Development Tools"
